version: '3.4'
services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    networks:
      - order-app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - mongodb:/data/db
    command: mongod --port 27018

    ports:
    - '27018:27018'
    networks:
      - order-app

volumes:
  mongodb:
    driver: local

networks:
  order-app:
    driver: bridge